#!/usr/bin/env python3
"""Emit host TZ offset for brs-engine Live TV EPG (GetTimeZoneOffset() is often 0 in sim)."""
from pathlib import Path
import time

OUT = Path(__file__).resolve().parents[1] / "source" / "lib" / "livetv" / "LiveTvDevTz.brs"

# Python: seconds west of UTC (IST → -19800). Roku: UTC = local + offsetMin*60.
offset_min = int(time.timezone / 60)
if time.daylight and time.localtime().tm_isdst:
    offset_min = int(time.altzone / 60)

OUT.write_text(
    f"""' Auto-generated by scripts/gen_livetv_dev_tz.py — host TZ for brs-engine simulator.
' Roku convention: UTC = local + offsetMin*60 (IST UTC+5:30 → -330).

function LT_DevHostTimeZoneOffsetMin() as integer
    return {offset_min}
end function
"""
)
print(f"Wrote {OUT} offsetMin={offset_min}")
