' Auto-generated by scripts/gen_livetv_dev_tz.py — host TZ for brs-engine simulator.
' Roku convention: UTC = local + offsetMin*60 (IST UTC+5:30 → -330).

function LT_DevHostTimeZoneOffsetMin() as integer
    return -330
end function
